# Generated by Django 3.2.7 on 2021-10-20 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='following_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='following_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
