# Generated by Django 3.2.7 on 2021-11-17 21:16

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_followers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.UsersManager()),
            ],
        ),
    ]
