version: "3.9"
volumes:
  easyblog_volume:

services:
  blog:
    container_name: easyblog-django
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - easyblog_volume:/app
      - ./db:/app/db
    restart: always
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    user: root    
  nginx:
    container_name: easyblog-nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile
    volumes:
      - easyblog_volume:/app
    links:
      - blog
    ports:
      - "8002:80"
    restart: always
    depends_on:
      - blog
  elasticsearch:
    container_name: easyblog-elasticsearch
    image: elasticsearch:7.16.3
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms256m -Xmx256m