version: "3.9"
volumes:
  blog_volume:

services:
  blog:
    container_name: django-easy-blog
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - blog_volume:/app
      - ./db:/app/db
    restart: always

  nginx:
    container_name: nginx-easy-blog
    build:
      context: .
      dockerfile: nginx.Dockerfile
    volumes:
      - blog_volume:/app
    ports:
      - "8002:80"
    restart: always
    depends_on:
      - blog