version: "3.9"
volumes:
  static:

services:
  blog:
    container_name: django-easy-blog
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static:/app/static
      - ./db:/app/db
    restart: always

  nginx:
    container_name: nginx-easy-blog
    build:
      context: .
      dockerfile: nginx.Dockerfile
    volumes:
      - static:/app/static
    links:
      - blog
    ports:
      - "8002:80"
    restart: always
    depends_on:
      - blog