# Generated by Django 3.2.7 on 2021-10-20 21:27

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='article',
            new_name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='raw_content',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='banner',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to=blog.models.get_banner_path, validators=[blog.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to=blog.models.get_avatar_path, validators=[blog.models.validate_file_size]),
        ),
    ]
