# Generated by Django 3.2.7 on 2021-10-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211020_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
