# Generated by Django 3.2.7 on 2021-10-27 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='raw_content',
        ),
    ]
