# Generated by Django 3.2.7 on 2021-09-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_report_reporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='send_follow_up',
            field=models.BooleanField(default=True),
        ),
    ]
